name: portable-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*' # Push events to matching v*, i.e. v1.0, v20.15.10
      
jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      targetZip: ikmultimedia-authorization-manager-portable-${{ github.ref_name }}.zip
    steps:
      - name: installer
        shell: bash
        run: |
          curl 'https://download.ikmultimedia.com/plugins/AuthorizationManager/Authorization_Manager_Windows_(1.0.26B).zip' \
            -H 'authority: download.ikmultimedia.com' \
            -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
            -H 'accept-language: en-US,en;q=0.9' \
            -H 'cache-control: no-cache' \
            -H 'pragma: no-cache' \
            -H 'referer: https://www.ikmultimedia.com/' \
            -H 'sec-ch-ua: "Chromium";v="107", "Not=A?Brand";v="24"' \
            -H 'sec-ch-ua-mobile: ?0' \
            -H 'sec-ch-ua-platform: "Windows"' \
            -H 'sec-fetch-dest: document' \
            -H 'sec-fetch-mode: navigate' \
            -H 'sec-fetch-site: same-site' \
            -H 'sec-fetch-user: ?1' \
            -H 'upgrade-insecure-requests: 1' \
            -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36' \
            --compressed -L --output installer.zip && 7z.exe x installer.zip
          
      - name: innoextract 
        shell: cmd
        run: | 
          curl https://github.com/dscharrer/innoextract/releases/download/1.9/innoextract-1.9-windows.zip -L --output innoextract-1.9-windows.zip &&^
          7z.exe x innoextract-1.9-windows.zip
          
      - shell: cmd
        run: |
          cd "Authorization Manager (1.0.26)" &&^
          ..\innoextract.exe "Installer Authorization Manager.exe"
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "Authorization\ Manager\ (1.0.26)/app"
          filename: "${{ env.targetZip }}"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Authorization\ Manager\ (1.0.26)/app/${{ env.targetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
