name: portable-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*' # Push events to matching v*, i.e. v1.0, v20.15.10
      
jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      targetZip: ikmultimedia-authorization-manager-portable-${{ github.ref_name }}.zip
    steps:
      - name: installer
        shell: cmd
        run: |
          curl https://download.ikmultimedia.com/plugins/AuthorizationManager/Authorization_Manager_Windows_(1.0.26B).zip -L -J --output installer.zip &&^
          7z.exe x installer.zip
          
      - name: innoextract 
        shell: cmd
        run: | 
          curl https://github.com/dscharrer/innoextract/releases/download/1.9/innoextract-1.9-windows.zip -L --output innoextract-1.9-windows.zip &&^
          7z.exe x innoextract-1.9-windows.zip
          
      - shell: cmd
        run: |
          cd "Authorization Manager (1.0.26)" &&^
          innoextract.exe "Installer Authorization Manager.exe"
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "Authorization Manager (1.0.26)/app"
          filename: "${{ env.targetZip }}"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Authorization Manager (1.0.26)/app/${{ env.targetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
